server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: springboot-helloworld-two
            client-secret: ssoClientSecret-2
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/helloworld/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/helloworld/protocol/openid-connect/token
            user-info-uri: http://localhost:8083/auth/realms/helloworld/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE

text:
  service:
    url: http://localhost:8082