spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              metadata-uri: https://dev-58841934.okta.com/app/exk744lnn5ttGLYGq5d7/sso/saml/metadata