apiVersion: v1
kind: Secret
metadata:
  name: helloworld-secret
data:
  message_hello_prop : SGVsbG8=
  message_world_prop : V29ybGQ=
  message_exclamation_prop : IQ==
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-container
  template:
    metadata:
      labels:
        app: helloworld-container
    spec:
      containers:
        - name: helloworld-container
          image: wisniewskikr/springboot-helloworld-message-flexible-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
          env:
          - name: message_hello
            valueFrom:
              secretKeyRef:
                name: helloworld-secret
                key: message_hello_prop
          - name: message_world
            valueFrom:
              secretKeyRef:
                name: helloworld-secret
                key: message_world_prop
          - name: message_exclamation
            valueFrom:
              secretKeyRef:
                name: helloworld-secret
                key: message_exclamation_prop
      volumes:
      - name: secret-volume
        secret:
          secretName: helloworld-secret      
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: helloworld-container